print ("Lab 1: Version Contol")
print ("Author:[MA. ANGELA C. BRISENIO]")
print ("Student ID: TUPM-25-3695")
print ("Lab 1: Version Control")
print ("Author:MA. Angela C. Brisenio")
print ("Student ID: TUPM-25-3695")
print ("Class Section: [1C]")
